[workspace]
members = ["access_file"]
resolver = "2"

[package]
name = "simple-svg"
version = "0.1.0"
edition = "2021"
license = "MIT"
exclude = ["/showcase"]

[dependencies]

[dev-dependencies]
pretty_assertions = "1.4.1"


